workInfo:
  title: "Fuga BWV 543"
  fullTitle: "Prelude and Fugue in A minor, BWV 543"
  composer: "J.S. Bach"
  workId: "bwv543"
  movementName: "Fuga"
  externalURL: "https://en.wikipedia.org/wiki/Prelude_and_Fugue_in_A_minor,_BWV_543"

files:
  svgPath: "bwv543_optimized.svg"
  notesPath: "bwv543_json_notes.json"
  audioPath: "bwv543_202506030923-80bpm.mp3"
  
musicalStructure:
  totalDurationSeconds: 337.0
  totalBars: 151
  visualLeadTimeSeconds: 0.2
